"""
Export API
==========

Generate PDF from chat content and PPTX from dashboards.
"""

import io
import re as _re
import tempfile
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse

router = APIRouter(prefix="/api/export", tags=["Export"])


def _get_user(request: Request) -> dict:
    user = getattr(getattr(request, 'state', None), 'user', None)
    if not user:
        raise HTTPException(401, "Not authenticated")
    return user


@router.post("/pdf")
async def export_pdf(request: Request):
    """Generate a PDF from markdown/HTML content."""
    _get_user(request)
    body = await request.json()
    content = body.get("content", "")
    title = _re.sub(r'[^\w\s\-.]', '', body.get("title", "Dash Export"))[:100] or 'export'

    if not content:
        raise HTTPException(400, "Content required")

    try:
        import markdown as md
        from weasyprint import HTML
    except ImportError:
        # Fallback: return HTML as downloadable file
        html_content = _build_html(title, content)
        buf = io.BytesIO(html_content.encode("utf-8"))
        return StreamingResponse(buf, media_type="text/html",
                                 headers={"Content-Disposition": f'attachment; filename="{title}.html"'})

    html_body = md.markdown(content, extensions=["tables", "fenced_code"])
    full_html = _build_html(title, html_body, is_raw_html=True)

    pdf_bytes = HTML(string=full_html).write_pdf()
    buf = io.BytesIO(pdf_bytes)
    return StreamingResponse(buf, media_type="application/pdf",
                             headers={"Content-Disposition": f'attachment; filename="{title}.pdf"'})


@router.post("/pptx")
async def export_pptx(request: Request):
    """Generate a PPTX from dashboard widgets or slides data."""
    _get_user(request)
    body = await request.json()
    title = _re.sub(r'[^\w\s\-.]', '', body.get("title", "Dash Report"))[:100] or 'export'
    slides = body.get("slides", [])

    if not slides:
        raise HTTPException(400, "Slides required")

    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        raise HTTPException(500, "python-pptx not installed")

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Generated by Dash"

    # Content slides
    blank_layout = prs.slide_layouts[len(prs.slide_layouts) - 1]  # truly blank
    for s in slides:
        slide = prs.slides.add_slide(blank_layout)
        # Remove all default placeholders
        for ph in list(slide.placeholders):
            sp = ph._element
            sp.getparent().remove(sp)
        # Title
        from pptx.util import Emu
        txBox = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12), Inches(0.8))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = s.get("title", "")
        p.font.size = Pt(24)
        p.font.bold = True

        # Content
        content = s.get("content", "")
        if content:
            txBox2 = slide.shapes.add_textbox(Inches(0.5), Inches(1.3), Inches(12), Inches(5.5))
            tf2 = txBox2.text_frame
            tf2.word_wrap = True
            # Split content into lines
            for line in content.split("\n"):
                p2 = tf2.add_paragraph()
                p2.text = line
                p2.font.size = Pt(14)

        # Table data
        headers = s.get("headers", [])
        rows = s.get("rows", [])
        if headers and rows:
            num_cols = len(headers)
            num_rows = min(len(rows), 15) + 1  # header + data rows
            left = Inches(0.5)
            top = Inches(1.5) if not content else Inches(4.0)
            width = Inches(12)
            height = Inches(0.3 * num_rows)

            table_shape = slide.shapes.add_table(num_rows, num_cols, left, top, width, height)
            table = table_shape.table

            for ci, h in enumerate(headers):
                cell = table.cell(0, ci)
                cell.text = h
                for paragraph in cell.text_frame.paragraphs:
                    paragraph.font.size = Pt(10)
                    paragraph.font.bold = True

            for ri, row in enumerate(rows[:15]):
                for ci, val in enumerate(row):
                    if ci < num_cols:
                        cell = table.cell(ri + 1, ci)
                        cell.text = str(val)
                        for paragraph in cell.text_frame.paragraphs:
                            paragraph.font.size = Pt(9)

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                             headers={"Content-Disposition": f'attachment; filename="{title}.pptx"'})


@router.post("/slides-agent")
async def slides_agent(request: Request):
    """Slide Agent: Think → Structure → Generate slides from chat."""
    _get_user(request)
    body = await request.json()
    messages = body.get("messages", [])
    title = _re.sub(r'[^\w\s\-.]', '', body.get("title", "Analysis Report"))[:100] or 'export'
    agent_name = body.get("agent_name", "Dash Agent")

    if not messages:
        raise HTTPException(400, "Messages required")

    convo = "\n\n".join(
        f"{'Q' if m.get('role') == 'user' else 'A'}: {m.get('content', '')[:1500]}"
        for m in messages[-20:]
    )

    from os import getenv
    import httpx, json
    from dash.settings import _repair_json

    api_key = getenv("OPENROUTER_API_KEY", "")
    thinking = {}
    slides = []

    if api_key:
        try:
            # ── LLM Call 1: THINK ──────────────────────────────────────
            think_prompt = f"""You are a McKinsey presentation strategist. Analyze this data analysis conversation and plan a compelling presentation.

CONVERSATION:
{convo[:5000]}

RULES:
1. Find the ONE key insight that would surprise the audience
2. Structure as: Situation → Complication → Resolution
3. Every slide title must be a FULL SENTENCE that states the insight (not a label)
   BAD: "Revenue by Channel"
   GOOD: "Ocean and Citymart drive 69% of revenue, but Citymart grows 2x faster"
4. Plan 6-8 slides

Return JSON:
{{
  "narrative": "The main story arc in one sentence",
  "key_insight": "The one surprising finding that changes perspective",
  "audience_action": "The specific action the audience should take",
  "slide_plan": [
    {{"title": "Full sentence insight", "layout": "cover|kpi|exhibit|data|comparison|trend|recommendations", "data_needed": "what numbers to extract"}}
  ]
}}"""

            think_resp = httpx.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={
                    "model": "openai/gpt-5.4-mini",
                    "messages": [{"role": "user", "content": think_prompt}],
                    "max_tokens": 2000,
                    "temperature": 0.3,
                },
                timeout=30,
            )
            think_raw = think_resp.json().get("choices", [{}])[0].get("message", {}).get("content", "")
            think_raw = _repair_json(think_raw)
            thinking = json.loads(think_raw)

            # ── LLM Call 2: GENERATE ───────────────────────────────────
            gen_prompt = f"""Generate McKinsey-style presentation slides. Every slide must follow these rules:

MCKINSKEY SLIDE RULES:
1. Title = Full sentence insight (NOT a label)
2. Every slide has an "action_line" starting with → that tells what to DO
3. Chart slides MUST have real numeric data extracted from the conversation
4. Table slides MUST have real data rows from the conversation
5. KPI slides MUST have 2-4 big numbers with labels and change indicators

PLAN: {json.dumps(thinking)}
ORIGINAL DATA: {convo[:4000]}

For each slide, generate this JSON:
{{
  "title": "Full sentence insight (the action title)",
  "layout": "cover|kpi|exhibit|data|comparison|recommendations",
  "topic": "Short topic label for header bar (2-3 words)",
  "bullets": ["numbered takeaway 1", "numbered takeaway 2", "numbered takeaway 3"],
  "chart": {{"type": "bar|line|pie|horizontal_bar", "labels": ["real label 1", "real label 2"], "values": [0, 0], "title": "Exhibit title"}},
  "table": {{"headers": ["Col1", "Col2", "Col3"], "rows": [["real data", "real data", "real data"]]}},
  "kpis": [{{"value": "2.60T", "label": "Total Revenue", "change": "+12%"}}, {{"value": "4.03B", "label": "Avg Daily", "change": "+5%"}}],
  "action_line": "→ Specific action the audience should take based on this slide",
  "comparison": {{"left": {{"title": "A", "items": ["metric: value"]}}, "right": {{"title": "B", "items": ["metric: value"]}}}}
}}

CRITICAL:
- chart, table, kpis, comparison are OPTIONAL — include only when layout matches
- Extract REAL numbers from the conversation — DO NOT use placeholder data
- First slide must be layout "cover"
- Last slide must be layout "recommendations" with 3-4 priority cards
- Include at least 2 slides with chart data
- Include at least 1 slide with a table

Return ONLY a valid JSON array of 6-8 slide objects."""

            gen_resp = httpx.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={
                    "model": "openai/gpt-5.4-mini",
                    "messages": [{"role": "user", "content": gen_prompt}],
                    "max_tokens": 4000,
                    "temperature": 0.2,
                },
                timeout=30,
            )
            gen_raw = gen_resp.json().get("choices", [{}])[0].get("message", {}).get("content", "")
            gen_raw = _repair_json(gen_raw)
            slides = json.loads(gen_raw)

        except Exception:
            pass

    # Fallback: basic slides from chat messages
    if not slides:
        slides = [
            {"title": title, "layout": "title", "bullets": [f"Generated by {agent_name}"], "so_what": "Overview"},
        ]
        for m in messages:
            if m.get("role") == "assistant" and m.get("content"):
                slides.append({
                    "title": "Analysis",
                    "layout": "bullets",
                    "bullets": [m["content"][:300]],
                    "so_what": "Key finding from conversation",
                })
        if not thinking:
            thinking = {"narrative": title, "key_insight": "See slides", "audience_action": "Review findings"}

    return {
        "status": "ok",
        "thinking": {
            "narrative": thinking.get("narrative", ""),
            "key_insight": thinking.get("key_insight", ""),
            "audience_action": thinking.get("audience_action", ""),
        },
        "slides": slides,
    }


@router.get("/presentations")
def list_presentations(request: Request, project: str):
    _get_user(request)
    from sqlalchemy import create_engine, text
    from db import db_url
    engine = create_engine(db_url)
    with engine.connect() as conn:
        rows = conn.execute(text(
            "SELECT id, title, version, thinking, created_at "
            "FROM public.dash_presentations WHERE project_slug = :s "
            "ORDER BY created_at DESC"
        ), {"s": project}).fetchall()
    return {"presentations": [
        {"id": r[0], "title": r[1], "version": r[2], "thinking": r[3], "created_at": str(r[4])}
        for r in rows
    ]}


@router.get("/presentations/{pres_id}")
def get_presentation(pres_id: int, request: Request):
    _get_user(request)
    from sqlalchemy import create_engine, text
    from db import db_url
    engine = create_engine(db_url)
    with engine.connect() as conn:
        row = conn.execute(text(
            "SELECT id, project_slug, title, version, thinking, slides, created_at "
            "FROM public.dash_presentations WHERE id = :id"
        ), {"id": pres_id}).fetchone()
    if not row:
        raise HTTPException(404, "Presentation not found")
    return {"id": row[0], "project_slug": row[1], "title": row[2], "version": row[3],
            "thinking": row[4], "slides": row[5], "created_at": str(row[6])}


@router.post("/presentations")
async def save_presentation(request: Request):
    _get_user(request)
    body = await request.json()
    project = body.get("project_slug", "")
    title = body.get("title", "Untitled")
    thinking = body.get("thinking", {})
    slides = body.get("slides", [])
    messages = body.get("source_messages", [])

    import json
    from sqlalchemy import create_engine, text
    from db import db_url
    engine = create_engine(db_url)
    with engine.connect() as conn:
        # Check if same title exists — increment version
        existing = conn.execute(text(
            "SELECT MAX(version) FROM public.dash_presentations WHERE project_slug = :s AND title = :t"
        ), {"s": project, "t": title}).scalar()
        version = (existing or 0) + 1

        result = conn.execute(text(
            "INSERT INTO public.dash_presentations (project_slug, title, version, thinking, slides, source_messages) "
            "VALUES (:s, :t, :v, CAST(:th AS jsonb), CAST(:sl AS jsonb), CAST(:msg AS jsonb)) RETURNING id"
        ), {"s": project, "t": title, "v": version, "th": json.dumps(thinking), "sl": json.dumps(slides), "msg": json.dumps(messages)})
        pres_id = result.fetchone()[0]
        conn.commit()
    return {"status": "ok", "id": pres_id, "version": version}


@router.delete("/presentations/{pres_id}")
def delete_presentation(pres_id: int, request: Request):
    _get_user(request)
    from sqlalchemy import create_engine, text
    from db import db_url
    engine = create_engine(db_url)
    with engine.connect() as conn:
        conn.execute(text("DELETE FROM public.dash_presentations WHERE id = :id"), {"id": pres_id})
        conn.commit()
    return {"status": "ok"}


@router.post("/presentations/{pres_id}/pptx")
def export_saved_pptx(pres_id: int, request: Request):
    _get_user(request)
    from sqlalchemy import create_engine, text
    from db import db_url
    engine = create_engine(db_url)
    with engine.connect() as conn:
        row = conn.execute(text(
            "SELECT title, slides FROM public.dash_presentations WHERE id = :id"
        ), {"id": pres_id}).fetchone()
    if not row:
        raise HTTPException(404, "Presentation not found")

    title = row[0]
    slides = row[1] if isinstance(row[1], list) else []

    # Build PPTX using python-pptx
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        raise HTTPException(500, "python-pptx not installed")

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Helper: add common slide elements
    def _add_header(slide, s, i, total):
        """Add topic bar, title, divider, slide number to a content slide."""
        # Topic bar
        tb = slide.shapes.add_textbox(Inches(0.3), Inches(0.15), Inches(10), Inches(0.25))
        tp = tb.text_frame.paragraphs[0]
        tp.text = s.get("topic", "ANALYSIS").upper()
        tp.font.size = Pt(8)
        tp.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
        # Slide number (top right)
        nb = slide.shapes.add_textbox(Inches(12), Inches(0.15), Inches(1), Inches(0.25))
        np2 = nb.text_frame.paragraphs[0]
        np2.text = f"{i+1} / {total}"
        np2.font.size = Pt(8)
        np2.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        np2.alignment = PP_ALIGN.RIGHT
        # Action title
        tb2 = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(12), Inches(1.0))
        tb2.text_frame.word_wrap = True
        p = tb2.text_frame.paragraphs[0]
        p.text = s.get("title", "")
        p.font.size = Pt(20)
        p.font.bold = True
        # Divider
        ln = slide.shapes.add_connector(1, Inches(0.5), Inches(1.5), Inches(12.5), Inches(1.5))
        ln.line.color.rgb = RGBColor(0xD2, 0x47, 0x26)
        ln.line.width = Pt(2)

    def _add_action_line(slide, s):
        """Add action line at bottom."""
        if s.get("action_line"):
            al = slide.shapes.add_connector(1, Inches(0.5), Inches(6.3), Inches(12.5), Inches(6.3))
            al.line.color.rgb = RGBColor(0x1a, 0x1a, 0x1a)
            al.line.width = Pt(1)
            ab = slide.shapes.add_textbox(Inches(0.5), Inches(6.4), Inches(12), Inches(0.5))
            ab.text_frame.word_wrap = True
            ap = ab.text_frame.paragraphs[0]
            ap.text = s["action_line"]
            ap.font.size = Pt(11)
            ap.font.bold = True

    def _add_bullets(slide, bullets, left=0.7, top=1.7, width=11.5, height=4.0):
        """Add bullet points."""
        if not bullets:
            return
        tb = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tb.text_frame.word_wrap = True
        for bi, b in enumerate(bullets[:8]):
            # Strip existing numbering like "1)" or "1."
            b_clean = b.lstrip("0123456789).·- ")
            p = tb.text_frame.add_paragraph() if bi > 0 else tb.text_frame.paragraphs[0]
            p.text = b_clean
            p.font.size = Pt(13)
            p.space_after = Pt(6)

    total = len(slides[:12])
    for i, s in enumerate(slides[:12]):
        layout = s.get("layout", "bullets")
        slide = prs.slides.add_slide(prs.slide_layouts[len(prs.slide_layouts) - 1])
        for ph in list(slide.placeholders):
            sp = ph._element
            sp.getparent().remove(sp)

        if layout == "cover":
            # Centered title
            tb = slide.shapes.add_textbox(Inches(1.5), Inches(2.0), Inches(10), Inches(2.0))
            tb.text_frame.word_wrap = True
            p = tb.text_frame.paragraphs[0]
            p.text = s.get("title", title)
            p.font.size = Pt(32)
            p.font.bold = True
            p.alignment = PP_ALIGN.CENTER
            # Orange line
            ln = slide.shapes.add_connector(1, Inches(5.5), Inches(4.2), Inches(7.8), Inches(4.2))
            ln.line.color.rgb = RGBColor(0xD2, 0x47, 0x26)
            ln.line.width = Pt(3)
            # Subtitle
            if s.get("bullets"):
                tb2 = slide.shapes.add_textbox(Inches(2), Inches(4.5), Inches(9), Inches(0.6))
                p2 = tb2.text_frame.paragraphs[0]
                p2.text = s["bullets"][0]
                p2.font.size = Pt(16)
                p2.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
                p2.alignment = PP_ALIGN.CENTER
            # Footer
            tb3 = slide.shapes.add_textbox(Inches(3), Inches(5.5), Inches(7), Inches(0.4))
            p3 = tb3.text_frame.paragraphs[0]
            p3.text = "POWERED BY RLAI DASH"
            p3.font.size = Pt(9)
            p3.font.color.rgb = RGBColor(0xBB, 0xBB, 0xBB)
            p3.alignment = PP_ALIGN.CENTER

        elif layout == "kpi" and s.get("kpis"):
            _add_header(slide, s, i, total)
            kpis = s["kpis"][:4]
            kpi_width = 11.0 / len(kpis)
            for ki, kpi in enumerate(kpis):
                left = 0.8 + ki * kpi_width
                # Value
                vb = slide.shapes.add_textbox(Inches(left), Inches(2.0), Inches(kpi_width - 0.3), Inches(1.0))
                vp = vb.text_frame.paragraphs[0]
                vp.text = str(kpi.get("value", ""))
                vp.font.size = Pt(36)
                vp.font.bold = True
                vp.alignment = PP_ALIGN.CENTER
                # Label
                lb = slide.shapes.add_textbox(Inches(left), Inches(3.0), Inches(kpi_width - 0.3), Inches(0.4))
                lp = lb.text_frame.paragraphs[0]
                lp.text = kpi.get("label", "").upper()
                lp.font.size = Pt(9)
                lp.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
                lp.alignment = PP_ALIGN.CENTER
                # Change
                if kpi.get("change"):
                    cb = slide.shapes.add_textbox(Inches(left), Inches(3.4), Inches(kpi_width - 0.3), Inches(0.4))
                    cp = cb.text_frame.paragraphs[0]
                    cp.text = kpi["change"]
                    cp.font.size = Pt(14)
                    cp.font.bold = True
                    is_pos = kpi["change"].startswith("+") or "▲" in kpi["change"]
                    cp.font.color.rgb = RGBColor(0x00, 0x87, 0x3c) if is_pos else RGBColor(0xD3, 0x2F, 0x2F)
                    cp.alignment = PP_ALIGN.CENTER
            _add_bullets(slide, s.get("bullets"), top=4.2, height=1.8)
            _add_action_line(slide, s)

        elif layout in ("exhibit", "trend") or s.get("chart"):
            _add_header(slide, s, i, total)
            chart = s.get("chart", {})
            labels = chart.get("labels", [])
            values = chart.get("values", [])
            chart_type = chart.get("type", "bar")

            if labels and values:
                try:
                    from pptx.chart.data import CategoryChartData
                    from pptx.enum.chart import XL_CHART_TYPE

                    chart_data = CategoryChartData()
                    chart_data.categories = [str(l) for l in labels[:12]]
                    chart_data.add_series("Value", [float(v) if isinstance(v, (int, float)) else 0 for v in values[:12]])

                    if chart_type == "pie":
                        xl_type = XL_CHART_TYPE.PIE
                    elif chart_type == "line":
                        xl_type = XL_CHART_TYPE.LINE
                    elif chart_type == "horizontal_bar":
                        xl_type = XL_CHART_TYPE.BAR_CLUSTERED
                    else:
                        xl_type = XL_CHART_TYPE.COLUMN_CLUSTERED

                    chart_shape = slide.shapes.add_chart(
                        xl_type, Inches(0.5), Inches(1.8), Inches(7), Inches(4.2), chart_data
                    )
                    pptx_chart = chart_shape.chart
                    pptx_chart.has_legend = False
                    if chart.get("title"):
                        pptx_chart.has_title = True
                        pptx_chart.chart_title.text_frame.paragraphs[0].text = chart["title"]
                        pptx_chart.chart_title.text_frame.paragraphs[0].font.size = Pt(10)

                    # Style the chart
                    try:
                        series = pptx_chart.series[0]
                        series.format.fill.solid()
                        series.format.fill.fore_color.rgb = RGBColor(0xD2, 0x47, 0x26)
                    except Exception:
                        pass

                except Exception:
                    # Fallback: render as table if chart fails
                    cb2 = slide.shapes.add_textbox(Inches(0.5), Inches(1.7), Inches(7), Inches(0.3))
                    cp2 = cb2.text_frame.paragraphs[0]
                    cp2.text = (chart.get("title", "EXHIBIT")).upper()
                    cp2.font.size = Pt(9)
                    cp2.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
                    num_rows = min(len(labels), 10) + 1
                    tbl = slide.shapes.add_table(num_rows, 2, Inches(0.5), Inches(2.1), Inches(6.5), Inches(0.35 * num_rows))
                    table = tbl.table
                    table.cell(0, 0).text = "Category"
                    table.cell(0, 1).text = "Value"
                    for ci2 in range(2):
                        for paragraph in table.cell(0, ci2).text_frame.paragraphs:
                            paragraph.font.size = Pt(9)
                            paragraph.font.bold = True
                    for ri2, (lbl, val) in enumerate(zip(labels[:10], values[:10])):
                        table.cell(ri2+1, 0).text = str(lbl)
                        table.cell(ri2+1, 1).text = f"{val:,.0f}" if isinstance(val, (int, float)) else str(val)

            # Takeaways on right
            _add_bullets(slide, s.get("bullets"), left=8.0, top=1.7, width=4.5, height=4.0)
            # Source
            sb = slide.shapes.add_textbox(Inches(0.5), Inches(6.0), Inches(4), Inches(0.3))
            sp = sb.text_frame.paragraphs[0]
            sp.text = "Source: Project data"
            sp.font.size = Pt(8)
            sp.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)
            _add_action_line(slide, s)

        elif layout == "data" or s.get("table"):
            _add_header(slide, s, i, total)
            tbl_data = s.get("table", {})
            headers = tbl_data.get("headers", [])
            rows = tbl_data.get("rows", [])[:10]
            if headers and rows:
                num_cols = min(len(headers), 6)
                num_rows = len(rows) + 1
                tbl = slide.shapes.add_table(num_rows, num_cols, Inches(0.5), Inches(1.8), Inches(12), Inches(0.35 * num_rows))
                table = tbl.table
                for ci, h in enumerate(headers[:num_cols]):
                    table.cell(0, ci).text = str(h)
                    for paragraph in table.cell(0, ci).text_frame.paragraphs:
                        paragraph.font.size = Pt(9)
                        paragraph.font.bold = True
                for ri, row in enumerate(rows):
                    for ci, val in enumerate(row[:num_cols]):
                        table.cell(ri+1, ci).text = str(val)
                        for paragraph in table.cell(ri+1, ci).text_frame.paragraphs:
                            paragraph.font.size = Pt(10)
            _add_bullets(slide, s.get("bullets"), top=1.8 + 0.35 * (len(rows) + 2), height=1.5)
            _add_action_line(slide, s)

        elif layout == "comparison" and s.get("comparison"):
            _add_header(slide, s, i, total)
            comp = s["comparison"]
            # Left box
            lb = slide.shapes.add_textbox(Inches(0.5), Inches(1.8), Inches(5.5), Inches(0.4))
            lp = lb.text_frame.paragraphs[0]
            lp.text = comp.get("left", {}).get("title", "A")
            lp.font.size = Pt(14)
            lp.font.bold = True
            lp.font.color.rgb = RGBColor(0xD2, 0x47, 0x26)
            # Left items
            left_items = comp.get("left", {}).get("items", [])
            for li, item in enumerate(left_items[:6]):
                ib = slide.shapes.add_textbox(Inches(0.7), Inches(2.4 + li * 0.4), Inches(5), Inches(0.35))
                ip = ib.text_frame.paragraphs[0]
                ip.text = item
                ip.font.size = Pt(12)
            # VS
            vb = slide.shapes.add_textbox(Inches(6.2), Inches(3.0), Inches(1), Inches(0.5))
            vp = vb.text_frame.paragraphs[0]
            vp.text = "vs"
            vp.font.size = Pt(18)
            vp.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
            vp.font.bold = True
            vp.alignment = PP_ALIGN.CENTER
            # Right box
            rb = slide.shapes.add_textbox(Inches(7.0), Inches(1.8), Inches(5.5), Inches(0.4))
            rp = rb.text_frame.paragraphs[0]
            rp.text = comp.get("right", {}).get("title", "B")
            rp.font.size = Pt(14)
            rp.font.bold = True
            rp.font.color.rgb = RGBColor(0x00, 0x87, 0x3c)
            # Right items
            right_items = comp.get("right", {}).get("items", [])
            for ri2, item in enumerate(right_items[:6]):
                ib2 = slide.shapes.add_textbox(Inches(7.2), Inches(2.4 + ri2 * 0.4), Inches(5), Inches(0.35))
                ip2 = ib2.text_frame.paragraphs[0]
                ip2.text = item
                ip2.font.size = Pt(12)
            _add_action_line(slide, s)

        elif layout == "recommendations":
            _add_header(slide, s, i, total)
            bullets = s.get("bullets", [])[:4]
            cols = 2
            for bi, b in enumerate(bullets):
                col = bi % cols
                row = bi // cols
                left = 0.5 + col * 6.2
                top = 1.8 + row * 2.2
                # Priority label
                pb = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(5.8), Inches(0.3))
                pp = pb.text_frame.paragraphs[0]
                pp.text = f"PRIORITY {bi+1}"
                pp.font.size = Pt(9)
                pp.font.bold = True
                pp.font.color.rgb = RGBColor(0xD2, 0x47, 0x26)
                # Content
                b_clean = b.lstrip("0123456789).·- ")
                cb2 = slide.shapes.add_textbox(Inches(left), Inches(top + 0.35), Inches(5.8), Inches(1.5))
                cb2.text_frame.word_wrap = True
                cp2 = cb2.text_frame.paragraphs[0]
                cp2.text = b_clean
                cp2.font.size = Pt(13)
            _add_action_line(slide, s)

        else:
            # Generic bullets
            _add_header(slide, s, i, total)
            _add_bullets(slide, s.get("bullets"), top=1.7, height=4.2)
            _add_action_line(slide, s)

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    safe_title = _re.sub(r'[^\w\s\-.]', '', title)[:100] or 'presentation'
    return StreamingResponse(buf, media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                             headers={"Content-Disposition": f'attachment; filename="{safe_title}.pptx"'})


@router.post("/pptx-from-chat")
async def export_pptx_from_chat(request: Request):
    """Generate a McKinsey-style PPTX from chat messages (workflow results)."""
    _get_user(request)
    body = await request.json()
    messages = body.get("messages", [])
    title = _re.sub(r'[^\w\s\-.]', '', body.get("title", "Analysis Report"))[:100] or 'export'

    if not messages:
        raise HTTPException(400, "Messages required")

    # Build conversation for LLM
    convo = "\n\n".join(f"{'Q' if m.get('role') == 'user' else 'A'}: {m.get('content', '')[:1500]}" for m in messages[-20:])

    from os import getenv
    import httpx
    api_key = getenv("OPENROUTER_API_KEY", "")

    # LLM: convert chat to slide structure
    slides_data = []
    if api_key:
        try:
            prompt = f"""Convert this data analysis conversation into presentation slides.

CONVERSATION:
{convo[:4000]}

Generate 5-8 slides as a JSON array. Each slide has:
- "title": short headline (max 10 words)
- "content": 3-5 bullet points (key findings, insights, numbers)
- "slide_type": one of "title", "findings", "data", "recommendation", "summary"

Rules:
- First slide: title slide with report name
- Include specific numbers/percentages from the data
- Last slide: recommendations or next steps
- Keep bullets concise (under 15 words each)
- Think like McKinsey — insight-driven, action-oriented

Return ONLY valid JSON array, no markdown."""

            resp = httpx.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={"model": "openai/gpt-5.4-mini", "messages": [{"role": "user", "content": prompt}], "max_tokens": 2000, "temperature": 0.3},
                timeout=30,
            )
            import json
            result = resp.json()
            content = result.get("choices", [{}])[0].get("message", {}).get("content", "")
            # Clean JSON
            content = content.strip()
            if content.startswith("```"):
                content = content.split("\n", 1)[-1]
            if content.endswith("```"):
                content = content[:-3]
            content = content.strip()
            if content.lower().startswith("json"):
                content = content[4:].strip()
            slides_data = json.loads(content)
        except Exception:
            pass

    # Fallback: one slide per message
    if not slides_data:
        slides_data = [{"title": title, "content": "Generated by Dash", "slide_type": "title"}]
        for m in messages:
            if m.get("role") == "assistant" and m.get("content"):
                text = m["content"][:500]
                slides_data.append({"title": "Analysis", "content": text, "slide_type": "findings"})

    # Build PPTX
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        raise HTTPException(500, "python-pptx not installed")

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    for i, s in enumerate(slides_data[:10]):
        slide_type = s.get("slide_type", "findings")
        slide = prs.slides.add_slide(prs.slide_layouts[len(prs.slide_layouts) - 1])  # truly blank
        # Remove all default placeholders
        for ph in list(slide.placeholders):
            sp = ph._element
            sp.getparent().remove(sp)

        if slide_type == "title":
            # Title slide — centered, large
            txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11), Inches(1.5))
            tf = txBox.text_frame
            p = tf.paragraphs[0]
            p.text = s.get("title", title)
            p.font.size = Pt(40)
            p.font.bold = True
            p.alignment = PP_ALIGN.CENTER

            txBox2 = slide.shapes.add_textbox(Inches(1), Inches(4.2), Inches(11), Inches(0.8))
            tf2 = txBox2.text_frame
            p2 = tf2.paragraphs[0]
            p2.text = s.get("content", "")
            p2.font.size = Pt(18)
            p2.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
            p2.alignment = PP_ALIGN.CENTER
        else:
            # Content slide — title + bullets
            # Title bar
            txBox = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12), Inches(0.8))
            tf = txBox.text_frame
            p = tf.paragraphs[0]
            p.text = s.get("title", "")
            p.font.size = Pt(28)
            p.font.bold = True
            p.font.color.rgb = RGBColor(0x1a, 0x1a, 0x1a)

            # Divider line
            from pptx.shapes.autoshape import Shape
            line = slide.shapes.add_connector(1, Inches(0.5), Inches(1.15), Inches(12.5), Inches(1.15))
            line.line.color.rgb = RGBColor(0x00, 0x96, 0x24)
            line.line.width = Pt(2)

            # Bullet content
            content = s.get("content", "")
            txBox2 = slide.shapes.add_textbox(Inches(0.7), Inches(1.4), Inches(11.5), Inches(5.5))
            tf2 = txBox2.text_frame
            tf2.word_wrap = True

            lines = content.split("\n") if "\n" in content else [content]
            for li, line_text in enumerate(lines):
                line_text = line_text.strip().lstrip("-•● ")
                if not line_text:
                    continue
                p2 = tf2.add_paragraph() if li > 0 else tf2.paragraphs[0]
                p2.text = f"  {line_text}"
                p2.font.size = Pt(16)
                p2.space_after = Pt(8)

            # Slide number
            txNum = slide.shapes.add_textbox(Inches(12.5), Inches(7.0), Inches(0.7), Inches(0.3))
            pNum = txNum.text_frame.paragraphs[0]
            pNum.text = str(i)
            pNum.font.size = Pt(9)
            pNum.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
            pNum.alignment = PP_ALIGN.RIGHT

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    safe_title = _re.sub(r'[^\w\s\-.]', '', title)[:100] or 'export'
    return StreamingResponse(buf, media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                             headers={"Content-Disposition": f'attachment; filename="{safe_title}.pptx"'})


@router.post("/slides-from-chat")
async def export_slides_from_chat(request: Request):
    """Generate beautiful HTML slide deck from chat messages with ECharts."""
    _get_user(request)
    body = await request.json()
    messages = body.get("messages", [])
    title = _re.sub(r'[^\w\s\-.]', '', body.get("title", "Analysis Report"))[:100] or 'export'
    agent_name = body.get("agent_name", "Dash Agent")

    if not messages:
        raise HTTPException(400, "Messages required")

    convo = "\n\n".join(f"{'Q' if m.get('role') == 'user' else 'A'}: {m.get('content', '')[:1500]}" for m in messages[-20:])

    from os import getenv
    import httpx, json
    api_key = getenv("OPENROUTER_API_KEY", "")

    slides_data = []
    if api_key:
        try:
            prompt = f"""Convert this data analysis conversation into a presentation slide deck.

CONVERSATION:
{convo[:5000]}

Generate 5-8 slides as a JSON array. Each slide object has:
- "title": headline (max 10 words)
- "bullets": array of 3-5 bullet strings (include specific numbers)
- "chart": optional chart object with {{"type": "bar"|"line"|"pie", "labels": ["A","B","C"], "values": [10,20,30], "title": "Chart Title"}}
- "table": optional table object with {{"headers": ["Col1","Col2"], "rows": [["a","1"],["b","2"]]}}
- "kpi": optional KPI object with {{"label": "Total Sales", "value": "$4.2M", "change": "+12%"}}
- "layout": "title" | "bullets" | "chart" | "table" | "kpi" | "split" | "summary"

Rules:
- Slide 1: layout="title" with report name
- Include at least 2 slides with chart data (extract real numbers from conversation)
- Include at least 1 slide with a table (extract data from conversation)
- Include 1 KPI slide with big numbers
- Last slide: layout="summary" with recommendations
- Extract REAL data from the conversation — use actual numbers, not placeholders

Return ONLY valid JSON array."""

            resp = httpx.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={"model": "openai/gpt-5.4-mini", "messages": [{"role": "user", "content": prompt}], "max_tokens": 3000, "temperature": 0.2},
                timeout=30,
            )
            content = resp.json().get("choices", [{}])[0].get("message", {}).get("content", "")
            content = content.strip()
            if content.startswith("```"): content = content.split("\n", 1)[-1]
            if content.endswith("```"): content = content[:-3]
            content = content.strip()
            if content.lower().startswith("json"): content = content[4:].strip()
            from dash.settings import _repair_json
            content = _repair_json(content)
            slides_data = json.loads(content)
        except Exception:
            pass

    if not slides_data:
        slides_data = [
            {"title": title, "bullets": [f"Generated by {agent_name}"], "layout": "title"},
            {"title": "Analysis", "bullets": [m.get("content", "")[:200] for m in messages if m.get("role") == "assistant"][:5], "layout": "bullets"},
        ]

    # Build HTML slide deck
    slide_html_parts = []
    for i, s in enumerate(slides_data[:10]):
        layout = s.get("layout", "bullets")
        slide_title = s.get("title", "")
        bullets = s.get("bullets", [])
        chart = s.get("chart")
        table = s.get("table")
        kpi = s.get("kpi")

        inner = ""

        if layout == "title":
            inner = f'''
                <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;">
                    <h1 style="font-size:56px;font-weight:900;margin:0;letter-spacing:-1px;">{slide_title}</h1>
                    <p style="font-size:22px;color:#666;margin-top:16px;">{"<br>".join(bullets)}</p>
                    <div style="margin-top:40px;font-size:13px;color:#999;text-transform:uppercase;letter-spacing:3px;">{agent_name} &middot; {__import__("datetime").date.today().strftime("%B %d, %Y")}</div>
                </div>'''

        elif layout == "kpi" and kpi:
            change_color = "#00c853" if kpi.get("change", "").startswith("+") else "#ff1744"
            inner = f'''
                <h2 style="font-size:28px;font-weight:900;margin-bottom:40px;">{slide_title}</h2>
                <div style="display:flex;align-items:center;justify-content:center;gap:60px;margin-top:40px;">
                    <div style="text-align:center;">
                        <div style="font-size:72px;font-weight:900;color:#1a1a1a;">{kpi.get("value","")}</div>
                        <div style="font-size:16px;color:#666;margin-top:8px;">{kpi.get("label","")}</div>
                        <div style="font-size:24px;font-weight:700;color:{change_color};margin-top:8px;">{kpi.get("change","")}</div>
                    </div>
                </div>
                {"".join(f"<div style='font-size:15px;color:#555;margin-top:8px;text-align:center;'>• {b}</div>" for b in bullets)}'''

        elif chart:
            chart_id = f"chart_{i}"
            chart_type = chart.get("type", "bar")
            labels = json.dumps(chart.get("labels", []))
            values = json.dumps(chart.get("values", []))
            chart_title = chart.get("title", "")

            if chart_type == "pie":
                chart_option = f"""{{
                    title: {{text:'{chart_title}',left:'center',textStyle:{{fontSize:14,fontWeight:700}}}},
                    tooltip: {{trigger:'item',formatter:'{{b}}: {{c}} ({{d}}%)'}},
                    series: [{{type:'pie',radius:['35%','65%'],data:{labels}.map((l,i)=>({{name:l,value:{values}[i]}})),
                        label:{{fontSize:12}},itemStyle:{{borderRadius:4,borderColor:'#fff',borderWidth:2}}}}]
                }}"""
            else:
                chart_option = f"""{{
                    tooltip: {{trigger:'axis'}},
                    title: {{text:'{chart_title}',left:'center',textStyle:{{fontSize:14,fontWeight:700}}}},
                    xAxis: {{type:'category',data:{labels},axisLabel:{{fontSize:11}}}},
                    yAxis: {{type:'value',axisLabel:{{fontSize:11}}}},
                    series: [{{type:'{chart_type}',data:{values},
                        itemStyle:{{color:'#009624',borderRadius:[4,4,0,0]}},
                        areaStyle: {chart_type == "line" and "{opacity:0.1}" or "undefined"},
                        smooth: {str(chart_type == "line").lower()}
                    }}],
                    grid: {{left:'8%',right:'5%',bottom:'12%',top:'18%'}}
                }}"""

            inner = f'''
                <h2 style="font-size:28px;font-weight:900;margin-bottom:12px;">{slide_title}</h2>
                <div style="display:flex;gap:30px;align-items:flex-start;">
                    <div style="flex:1;">
                        <div id="{chart_id}" style="width:100%;height:340px;"></div>
                        <script>echarts.init(document.getElementById('{chart_id}')).setOption({chart_option});</script>
                    </div>
                    <div style="flex:0 0 280px;padding-top:20px;">
                        {"".join(f"<div style='font-size:14px;color:#333;margin-bottom:10px;padding-left:14px;border-left:3px solid #009624;'>{ b}</div>" for b in bullets)}
                    </div>
                </div>'''

        elif table:
            headers = table.get("headers", [])
            rows = table.get("rows", [])
            th = "".join(f"<th style='padding:8px 14px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#666;border-bottom:2px solid #1a1a1a;'>{h}</th>" for h in headers)
            trs = ""
            for ri, row in enumerate(rows[:12]):
                bg = "#f9f9f6" if ri % 2 == 0 else "#fff"
                tds = "".join(f"<td style='padding:7px 14px;font-size:13px;border-bottom:1px solid #eee;'>{v}</td>" for v in row)
                trs += f"<tr style='background:{bg};'>{tds}</tr>"
            inner = f'''
                <h2 style="font-size:28px;font-weight:900;margin-bottom:16px;">{slide_title}</h2>
                <table style="width:100%;border-collapse:collapse;"><thead><tr>{th}</tr></thead><tbody>{trs}</tbody></table>
                <div style="margin-top:16px;">{"".join(f"<div style='font-size:13px;color:#555;margin-bottom:6px;'>• {b}</div>" for b in bullets)}</div>'''

        elif layout == "summary":
            inner = f'''
                <h2 style="font-size:28px;font-weight:900;margin-bottom:24px;">{slide_title}</h2>
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">
                    {"".join(f"<div style='padding:16px;border:2px solid #1a1a1a;background:#f9f9f6;'><div style='font-size:14px;font-weight:700;margin-bottom:4px;'>→</div><div style='font-size:14px;color:#333;'>{b}</div></div>" for b in bullets)}
                </div>'''

        else:  # bullets
            inner = f'''
                <h2 style="font-size:28px;font-weight:900;margin-bottom:24px;">{slide_title}</h2>
                {"".join(f"<div style='font-size:18px;color:#333;margin-bottom:14px;padding:12px 16px;border-left:4px solid #009624;background:#f9f9f6;'>{b}</div>" for b in bullets)}'''

        slide_html_parts.append(f'''
            <div class="slide" id="slide-{i}">
                <div class="slide-content">{inner}</div>
                <div class="slide-footer">
                    <span>{agent_name}</span>
                    <span>{i + 1} / {len(slides_data[:10])}</span>
                </div>
            </div>''')

    html = f"""<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:'Helvetica Neue',Arial,sans-serif; background:#1a1a1a; overflow:hidden; }}
.slide {{ width:100vw; height:100vh; background:#fff; display:none; padding:50px 60px; position:relative; }}
.slide.active {{ display:flex; flex-direction:column; }}
.slide-content {{ flex:1; }}
.slide-footer {{ display:flex; justify-content:space-between; font-size:11px; color:#999; text-transform:uppercase; letter-spacing:2px; padding-top:16px; border-top:1px solid #eee; }}
.nav {{ position:fixed; bottom:20px; left:50%; transform:translateX(-50%); display:flex; gap:8px; z-index:100; background:rgba(0,0,0,0.8); padding:8px 16px; border-radius:8px; }}
.nav button {{ background:none; border:1px solid #666; color:#fff; padding:6px 14px; cursor:pointer; font-size:11px; border-radius:4px; text-transform:uppercase; }}
.nav button:hover {{ background:#333; }}
.nav .current {{ color:#aaa; font-size:11px; padding:6px 8px; }}
h1,h2 {{ color:#1a1a1a; }}
@media print {{ .nav {{ display:none; }} .slide {{ page-break-after:always; display:flex !important; }} }}
</style>
</head><body>
{"".join(slide_html_parts)}
<div class="nav">
    <button onclick="go(-1)">← PREV</button>
    <span class="current" id="page-num">1 / {len(slides_data[:10])}</span>
    <button onclick="go(1)">NEXT →</button>
    <button onclick="window.print()">PRINT / PDF</button>
</div>
<script>
let cur = 0;
const slides = document.querySelectorAll('.slide');
const total = slides.length;
function show(n) {{ slides.forEach(s => s.classList.remove('active')); slides[n].classList.add('active'); document.getElementById('page-num').textContent = (n+1)+' / '+total; }}
function go(d) {{ cur = Math.max(0, Math.min(total-1, cur+d)); show(cur); }}
document.addEventListener('keydown', e => {{ if(e.key==='ArrowRight'||e.key===' ') go(1); if(e.key==='ArrowLeft') go(-1); if(e.key==='f') document.documentElement.requestFullscreen(); }});
show(0);
</script>
</body></html>"""

    buf = io.BytesIO(html.encode("utf-8"))
    safe_title = _re.sub(r'[^\w\s\-.]', '', title)[:100] or 'export'
    return StreamingResponse(buf, media_type="text/html",
                             headers={"Content-Disposition": f'attachment; filename="{safe_title}-slides.html"'})


@router.post("/report-from-chat")
async def generate_report_from_chat(request: Request):
    """Generate a structured report from a chat session."""
    _get_user(request)
    body = await request.json()
    messages = body.get("messages", [])
    title = _re.sub(r'[^\w\s\-.]', '', body.get("title", "Analysis Report"))[:100] or 'export'

    if not messages:
        raise HTTPException(400, "Messages required")

    # Build conversation text
    convo = "\n\n".join(f"{'Q' if m.get('role') == 'user' else 'A'}: {m.get('content', '')}" for m in messages)

    from os import getenv
    import httpx
    api_key = getenv("OPENROUTER_API_KEY", "")

    report_content = f"# {title}\n\n"
    if api_key:
        try:
            prompt = f"""Convert this data analysis conversation into a structured report.

CONVERSATION:
{convo[:3000]}

Generate a professional report with these sections:
1. Executive Summary (2-3 sentences)
2. Key Findings (bullet points)
3. Data Analysis (details with any tables/numbers mentioned)
4. Recommendations (if applicable)

Write in markdown format."""

            resp = httpx.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={"model": "openai/gpt-5.4-mini", "messages": [{"role": "user", "content": prompt}], "max_tokens": 2000, "temperature": 0.2},
                timeout=20,
            )
            result = resp.json()
            report_content = result.get("choices", [{}])[0].get("message", {}).get("content", report_content)
        except Exception:
            # Fallback: just concatenate the conversation
            report_content += convo
    else:
        report_content += convo

    try:
        import markdown as md
        from weasyprint import HTML
        html_body = md.markdown(report_content, extensions=["tables", "fenced_code"])
        full_html = _build_html(title, html_body, is_raw_html=True)
        pdf_bytes = HTML(string=full_html).write_pdf()
        buf = io.BytesIO(pdf_bytes)
        return StreamingResponse(buf, media_type="application/pdf",
                                 headers={"Content-Disposition": f'attachment; filename="{title}.pdf"'})
    except ImportError:
        html_content = _build_html(title, report_content)
        buf = io.BytesIO(html_content.encode("utf-8"))
        return StreamingResponse(buf, media_type="text/html",
                                 headers={"Content-Disposition": f'attachment; filename="{title}.html"'})


def _build_html(title: str, body: str, is_raw_html: bool = False) -> str:
    """Build a full HTML document with print-friendly styling."""
    import markdown as md

    if not is_raw_html:
        body = md.markdown(body, extensions=["tables", "fenced_code"])

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; font-size: 14px; line-height: 1.6; }}
  h1 {{ font-size: 24px; border-bottom: 2px solid #333; padding-bottom: 8px; }}
  h2 {{ font-size: 18px; margin-top: 24px; }}
  h3 {{ font-size: 15px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 12px; }}
  th {{ background: #333; color: #fff; padding: 6px 10px; text-align: left; font-weight: 700; }}
  td {{ padding: 5px 10px; border: 1px solid #ddd; }}
  tr:nth-child(even) td {{ background: #f9f9f9; }}
  code {{ background: #f0f0f0; padding: 1px 4px; font-size: 12px; }}
  pre {{ background: #333; color: #0f0; padding: 12px; overflow-x: auto; font-size: 12px; }}
  pre code {{ background: none; color: inherit; }}
  .header {{ text-align: center; margin-bottom: 30px; }}
  .footer {{ margin-top: 40px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }}
</style>
</head>
<body>
<div class="header"><h1>{title}</h1></div>
{body}
<div class="footer">Generated by Dash Data Agent</div>
</body>
</html>"""
